jocosocial/twitarr

app/controllers/api/v2/user_controller.rb, config/routes.rb
=> Added api endpoint for user creation

app/models/concerns/postable.rb
Use find_one_and_replace instead.
=> Fix like/unlike: mongoid deprecated find_and_modify.

config/initializers/filter_parameter_logging.rb, config/routes.rb
Ensure seamails come in json format
Hide security_answer from logging
=> Minor API updates

app/assets/javascripts/controllers/admin_controllers.js.coffee, app/assets/javascripts/routes/admin_routes.js.coffee, app/assets/javascripts/templates/admin/upload_schedule.hbs, app/controllers/api/v2/admin_controller.rb, app/controllers/api/v2/user_controller.rb, config/routes.rb
When updating user profile, validate password requirements
Add admin functions to api/v2
Update ember admin pages to use api/v2 endpoints
=> User password change validation fix, api/v2 admin endpoints

app/assets/javascripts/controllers/application_controller.js.coffee, app/assets/javascripts/controllers/user_controllers.js.coffee, app/assets/javascripts/models/starred.js.coffee, app/assets/javascripts/routes/application_routes.js.coffee, app/assets/javascripts/templates/user/profile.hbs, app/controllers/api/v2/text_controller.rb, app/controllers/api/v2/user_controller.rb, config/routes.rb, public/text/helptext.json
Application controller - use api/v2 endpoints for everything
Added password change needed flag to api/v2/user/whoami
Added password change check to login
Added info about the password change needed alert to the help screen
Updated application_routes to point to api/v2
Added api/v2 time endpoint to the text controller
Added api/v2 endpoint for personal comments on user profiles 
Migrated starred to api/v2
Added personal comment to user profile page (previously only on starred)
Fixed viewing larger version of user profile photo
=> api/v2 migrations, usability updates, bug fixes

app/assets/javascripts/controllers/application_controller.js.coffee, app/assets/javascripts/controllers/stream_controllers.js.coffee, app/assets/javascripts/controllers/user_controllers.js.coffee, app/assets/javascripts/templates/stream/view.hbs, app/assets/javascripts/templates/upload.hbs, app/assets/javascripts/templates/user/profile.hbs, app/controllers/api/v2/photo_controller.rb, app/controllers/application_controller.rb, config/routes.rb
Added missing api/v2 routes for photos
Check that user exists when doing a logged in test
Clear login form error on successful login
Hide some things that should be hidden when logged out
=> Added missing api/v2/photo endpoints, fixed some bugs

app/models/user.rb
=> Change email regex

app/controllers/api/v2/text_controller.rb
=> Added offset to time endpoint

app/controllers/api/v2/seamail_controller.rb, app/decorators/seamail_message_decorator.rb, rest_documentation.md
Documentation updates.
Added option to seamail show thread to allow not marking as read
Added ID to output of seamail messages
=> Documentation updates, new parameter for seamail thread, output seamail message ids

app/controllers/api/v2/alerts_controller.rb, app/controllers/api/v2/seamail_controller.rb, app/decorators/seamail_decorator.rb, app/decorators/seamail_message_decorator.rb, rest_documentation.md
=> Updated seamail threads endpoint to allow exclusion of read messages, Added disambiguation for message counts, Updated documentation

app/assets/javascripts/helpers/pretty_message_count.js.coffee, app/assets/javascripts/models/seamail.js.coffee, app/assets/javascripts/routes/application_routes.js.coffee, app/assets/javascripts/templates/seamail/meta_partial.hbs, app/controllers/api/v2/alerts_controller.rb, app/controllers/api/v2/seamail_controller.rb, app/decorators/seamail_decorator.rb, app/models/user.rb, rest_documentation.md
=> Changed message_count to integer, added flag to track if unread count

app/assets/javascripts/controllers/user_controllers.js.coffee, app/assets/javascripts/models/user.js.coffee, app/assets/javascripts/routes/user_routes.js.coffee, app/assets/javascripts/templates/user/forgot_password.hbs, app/assets/javascripts/templates/user/new.hbs, app/controllers/api/v2/user_controller.rb, app/models/user.rb, config/routes.rb
Remove security question and security answer
Change reset password to use registration code instead
Make e-mail optional and remove from account creation
=> User updates

app/assets/javascripts/controllers/stream_controllers.js.coffee, app/assets/javascripts/mixins/multiple_photo_upload.js.coffee, app/assets/javascripts/mixins/single_photo_upload.js.coffee, app/assets/javascripts/templates/upload.hbs, app/assets/javascripts/views/upload_view.js.coffee, app/controllers/api/v2/photo_controller.rb, app/decorators/forum_post_decorator.rb, app/decorators/stream_post_decorator.rb, app/models/photo_store.rb, rest_documentation.md
=> Fixes and enhancements for photo uploads.

app/assets/javascripts/models/user.js.coffee, app/assets/javascripts/templates/user/index.hbs, app/assets/javascripts/templates/user/profile.hbs, app/controllers/api/v2/user_controller.rb, app/decorators/user_decorator.rb, app/models/user.rb, rest_documentation.md
=> Removed user.email_public, Added user.pronouns, Updated profile layout

app/assets/javascripts/templates/admin/user_partial.hbs, app/controllers/api/v2/event_controller.rb, app/controllers/api/v2/photo_controller.rb, app/controllers/api/v2/stream_controller.rb, app/controllers/api/v2/user_controller.rb, app/controllers/application_controller.rb, app/decorators/announcement_decorator.rb, app/decorators/event_decorator.rb, app/decorators/forum_decorator.rb, app/decorators/forum_post_decorator.rb, app/decorators/photo_metadata_decorator.rb, app/decorators/post_reaction_decorator.rb, app/decorators/seamail_decorator.rb, app/decorators/seamail_message_decorator.rb, app/decorators/stream_post_decorator.rb, app/decorators/user_decorator.rb, app/models/concerns/postable.rb, app/models/forum.rb, app/models/time.rb, app/models/user.rb, rest_documentation.md
Also, try to be flexible with datetime input - accept epoch or formatted date
=> Always return epoch when getting a datetime out of the API

public/text/helptext.json
=> Added helptext for starring users/starred stream

app/controllers/api/v2/user_controller.rb, app/models/photo_store.rb, config/routes.rb, rest_documentation.md
Streamlined user controller, and a few bugfixes
=> User documentation updates

app/assets/javascripts/helpers/time.js.coffee, app/assets/javascripts/templates/admin/announcements.hbs, app/controllers/api/v2/text_controller.rb, public/text/codeofconduct.json, rest_documentation.md
=> Documentation for text endpoints

app/models/user.rb, rest_documentation.md
=> Set max length for username, update username & displayname errors

app/controllers/api/v2/forums_controller.rb, app/controllers/api/v2/photo_controller.rb, app/controllers/api/v2/stream_controller.rb
allow moderators to delete content
allow tho to modify content
=> Update authorization checks

app/assets/javascripts/controllers/forums_controllers.js.coffee, app/assets/javascripts/controllers/stream_controllers.js.coffee, app/assets/javascripts/templates/forums/post_partial.hbs, app/assets/javascripts/templates/stream/post_partial.hbs
=> Hide unlike link when logged out

app/assets/javascripts/routes/admin_routes.js.coffee, app/assets/javascripts/routes/search_routes.js.coffee
=> Fixed search page

app/assets/javascripts/templates/stream/post_partial.hbs, app/assets/stylesheets/main.css.scss, app/decorators/base_decorator.rb
=> Tweet stream: make the timestamp the view thread link, instead of the full post

app/assets/javascripts/templates/time.hbs
=> Updated text on the time page

app/assets/javascripts/controllers/forums_controllers.js.coffee, app/assets/javascripts/templates/starred.hbs, app/assets/javascripts/templates/user/profile.hbs
=> UI Updates - scrolling offsets, personal comment label

app/assets/javascripts/controllers/forums_controllers.js.coffee, app/assets/javascripts/controllers/stream_controllers.js.coffee, app/assets/javascripts/models/forum.js.coffee, app/assets/javascripts/models/stream.js.coffee, app/assets/javascripts/routes/forums_routes.js.coffee, app/assets/javascripts/routes/stream_routes.coffee, app/assets/javascripts/templates/forums/detail.hbs, app/assets/javascripts/templates/forums/new.hbs, app/assets/javascripts/templates/stream/page.hbs, app/assets/javascripts/templates/stream/view.hbs, app/controllers/api/v2/forums_controller.rb, app/controllers/api/v2/stream_controller.rb, app/controllers/application_controller.rb, app/models/concerns/postable.rb, app/models/forum.rb, app/models/forum_post.rb, app/models/stream_post.rb, db/seeds/development.rb, db/seeds/production.rb, db/seeds/test.rb, rest_documentation.md
Allow users with privs to post as moderator
Include moderator account in seeds
Track original author of post so moderators are accountable
=> Post as Moderator

app/decorators/forum_post_decorator.rb, app/decorators/photo_metadata_decorator.rb, app/decorators/stream_post_decorator.rb, app/models/photo_metadata.rb, app/models/photo_store.rb, rest_documentation.md
Return an array of available sizes with photo metadata
Don't resize image for medium_thumb if it's already smaller than the size limit
=> Photo Updates

app/assets/javascripts/templates/application.hbs, app/assets/javascripts/templates/seamail/index.hbs
Added direct link to moderator seamail in main menu
=> Updated moderator seamail header

app/assets/javascripts/controllers/stream_controllers.js.coffee, app/assets/javascripts/templates/admin/profile.hbs, app/assets/javascripts/templates/application.hbs, app/assets/javascripts/templates/forums/controls_partial.hbs, app/assets/javascripts/templates/forums/detail.hbs, app/assets/javascripts/templates/forums/post_partial.hbs, app/assets/javascripts/templates/schedule/detail.hbs, app/assets/javascripts/templates/schedule/meta_partial.hbs, app/assets/javascripts/templates/seamail/meta_partial.hbs, app/assets/javascripts/templates/stream/page.hbs, app/assets/javascripts/templates/stream/post_partial.hbs, app/assets/javascripts/templates/stream/view.hbs, app/assets/javascripts/templates/user/profile.hbs
Added missing glyphicons in main menu
Use if blocks for hiding/showing controls instead of hidden class
=> Front-end updates

.gitignore, app/assets/javascripts/routes/admin_routes.js.coffee, app/assets/javascripts/templates/admin/profile.hbs, app/controllers/api/v2/admin_controller.rb, app/models/registration_code.rb, app/models/user.rb, config/routes.rb, db/seeds/development.rb, db/seeds/production.rb, rest_documentation.md
Added endpoint for looking up user's registration code
Added front-end button to look up registration code
Production seed: check for regcode file and popuolate codes if present
Update rest documentation's permissions for admin endpoints
Prevent non-admins from changing admin roles
=> Registration code and admin updates

app/controllers/api/v2/user_controller.rb, app/models/user.rb, rest_documentation.md
=> Added max length of 100 characters to passwords

app/assets/javascripts/router.js.coffee, app/assets/javascripts/routes/application_routes.js.coffee, app/assets/javascripts/templates/application.hbs, app/assets/javascripts/templates/conduct.hbs, app/assets/javascripts/templates/time.hbs, app/assets/javascripts/templates/user/login.hbs, app/assets/javascripts/templates/user/new.hbs, app/models/seamail.rb, public/text/codeofconduct.json, public/text/helptext.json, rest_documentation.md
Changed text instances of Twitarr to Twit-arr
Updates to helptext and code of conduct
Added front-end page for code of conduct
Added links to code of conduct in a few relevant spots
=> Text Updates

app/controllers/api/v2/user_controller.rb, app/controllers/application_controller.rb, rest_documentation.md
Add expiration, include hashed pass in the digest
Provide new key on user password change
=> Updated key generation and checking

app/models/forum_post.rb, app/models/stream_post.rb
Forum posts - update hashtags when editing, too
=> Update for reparent_children

app/assets/javascripts/controllers/stream_controllers.js.coffee, app/assets/javascripts/models/stream.js.coffee, app/assets/javascripts/router.js.coffee, app/assets/javascripts/routes/stream_routes.coffee, app/assets/javascripts/templates/alerts.hbs, app/assets/javascripts/templates/stream/author_page.hbs, app/assets/javascripts/templates/stream/mentions_page.hbs, app/assets/javascripts/templates/user/profile.hbs, db/seeds/development.rb, db/seeds/production.rb, db/seeds/test.rb
All mentions for a user
All tweets by a user
=> New tweet stream pages

app/assets/javascripts/routes/event_routes.js.coffee, app/assets/javascripts/routes/schedule_routes.js.coffee, app/assets/javascripts/routes/seamail_routes.js.coffee, app/assets/javascripts/routes/search_routes.js.coffee, app/assets/javascripts/routes/user_routes.js.coffee, app/assets/javascripts/templates/admin/sections.hbs, app/controllers/api/v2/event_controller.rb, app/controllers/api/v2/forums_controller.rb, app/controllers/api/v2/seamail_controller.rb, app/controllers/api/v2/search_controller.rb, app/controllers/api/v2/stream_controller.rb, app/controllers/api/v2/user_controller.rb, app/controllers/application_controller.rb, db/seeds/development.rb, db/seeds/production.rb, db/seeds/test.rb, rest_documentation.md
Added section controls for more sections
Moved section check definitions to the applicaton controller
Changed status code for disabled sections to 503
Highlight disabled sections on the admin page
=> Section control updates

rest_documentation.md
=> Fixed forums delete endpoint in documentation #247

app/assets/javascripts/controllers/forums_controllers.js.coffee, app/assets/javascripts/routes/application_routes.js.coffee, app/assets/javascripts/templates/alerts.hbs, app/controllers/api/v2/alerts_controller.rb, app/models/user.rb, config/initializers/utilities.rb
Fix query for upcoming events
Fix decoration of forums alerts
Add button to mark alerts as read, only mark alerts as read when button is clicked
=> Alert Updates

app/assets/javascripts/controllers/forums_controllers.js.coffee, app/assets/javascripts/models/forum.js.coffee, app/assets/javascripts/templates/forums/detail.hbs, app/assets/stylesheets/main.css.scss, app/decorators/forum_decorator.rb, app/models/user.rb, db/seeds/all.ics, public/text/helptext.json, rest_documentation.md
Add new forum paging to forum thread view
Change event alert look-ahead from 3 hours to 2 hours
Fix pointer for navigation tabs
Updated schedule seed
Updated helptext
=> Updated paging on forum thread view, misc fixes

app/assets/javascripts/controllers/stream_controllers.js.coffee, app/assets/javascripts/templates/forums/detail.hbs, app/assets/javascripts/templates/forums/edit.hbs, app/assets/javascripts/templates/forums/new.hbs, app/assets/javascripts/templates/seamail/detail.hbs, app/assets/javascripts/templates/seamail/new.hbs, app/assets/javascripts/templates/stream/edit.hbs, app/assets/javascripts/templates/stream/page.hbs, app/assets/javascripts/templates/stream/view.hbs
=> Added Code of Conduct reminders

.overcommit.yml, Gemfile, Gemfile.lock, app/controllers/api/v2/admin_controller.rb, app/controllers/api/v2/alerts_controller.rb, app/controllers/api/v2/forums_controller.rb, app/controllers/api/v2/photo_controller.rb, app/controllers/api/v2/seamail_controller.rb, app/controllers/api/v2/stream_controller.rb, app/controllers/application_controller.rb, app/decorators/base_decorator.rb, app/decorators/seamail_decorator.rb, app/decorators/seamail_message_decorator.rb, app/helpers/identicon.rb, app/models/concerns/postable.rb, app/models/event.rb, app/models/photo_store.rb, app/models/seamail.rb, app/models/seamail_message.rb, app/models/stream_post.rb, app/models/user.rb, app/models/user_seamail.rb, db/migrate/20191217050310_create_seamails.rb, db/migrate/20191217050326_create_seamail_messages.rb, db/migrate/20191217050340_create_user_seamails.rb, db/structure.sql, rest_documentation.md
Also includes updates to photos, fixes for all rubocop issues, and a commit hook to enforce rubocop compliance
=> Ported Seamail to Postgres

.rubocop.yml, app/controllers/api/v2/photo_controller.rb, app/models/seamail.rb, config/application.rb, config/environments/development.rb, lib/tasks/auto_annotate_models.rake
Also fix new rubocop issues post-gem-upgrade.
Fixes #287
=> Fix return value for seamail#add_message

app/models/forum.rb
=> Only use custom validator for forum posts

app/models/seamail.rb, app/models/seamail_message.rb
=> Fix read_users for new seamails

app/controllers/api/v2/search_controller.rb
=> Disable search endpoints when sections are disabled

app/controllers/api/v2/forums_controller.rb, app/decorators/post_reaction_decorator.rb, app/models/concerns/postable.rb, app/models/forum_post.rb
=> Fix reactions on forum threads, fix reaction output format

app/controllers/api/v2/forums_controller.rb
=> More nil safety when checking for locked forums

app/models/photo_metadata.rb, app/models/post_photo.rb, db/migrate/20200209044205_change_photo_metadata_pkey.rb, db/structure.sql
=> Change photo ids to uuid

app/models/hashtag.rb
=> Fix hashtag autocomplete

app/controllers/api/v2/event_controller.rb, app/models/event.rb, rest_documentation.md
=> Fix event unfollow

app/controllers/api/v2/admin_controller.rb, app/models/section.rb, db/migrate/20200215191244_index_sections_by_category.rb, db/seeds/development.rb, db/seeds/production.rb, db/seeds/test.rb, db/structure.sql, rest_documentation.md
Allow filtering sections by category
=> Additional sections for cruise monkey and rainbow monkey

app/assets/javascripts/controllers/seamail_controller.js.coffee, app/assets/javascripts/controllers/user_controllers.js.coffee, app/assets/javascripts/router.js.coffee, app/assets/javascripts/routes/seamail_routes.js.coffee, app/assets/javascripts/templates/user/profile.hbs
=> Initiate a seamail from user profile

app/models/user.rb
=> Allow searching users by real name

app/assets/stylesheets/main.css.scss, app/decorators/event_decorator.rb, app/models/forum.rb, app/models/user.rb, app/models/user_forum_view.rb
Shorter cache key names, fix events bottom nav, slight improvement to event decorator
=> Minor tweaks

app/controllers/api/v2/hashtag_controller.rb
I am not a Ruby programmer. I do not understand the Ruby language.
Should that stop me from submitting bugfixes to a Ruby sourcebase? I mean, probably, yeah.
This is a very simple one line change; even so, someone who at least knows the language should probably look at it before merging.
=> Fixes #361.

app/assets/javascripts/models/karaoke.js.coffee, app/assets/javascripts/templates/karaoke.hbs
Use reduce to search karaoke - it's more efficient
Make naming of karaoke list attributes a bit more clear
=> Karaoke improvements

app/decorators/announcement_decorator.rb, app/decorators/forum_decorator.rb, app/decorators/forum_post_decorator.rb, app/decorators/post_reaction_decorator.rb, app/decorators/seamail_decorator.rb, app/decorators/seamail_message_decorator.rb, app/decorators/stream_post_decorator.rb, app/decorators/user_decorator.rb, rest_documentation.md
Also, actually use the abbreviated user hash in other decorators.
=> Add pronouns to abbreviated user hash

app/decorators/user_decorator.rb, app/models/user.rb, rest_documentation.md
Also add some memorization on repeated queries for alerts checking
=> Remove unnoticed_alerts from whoami

app/controllers/api/v2/forums_controller.rb, app/decorators/forum_decorator.rb, app/decorators/forum_post_decorator.rb, app/models/forum.rb, app/models/forum_post.rb, db/seeds/development.rb
Performance improvements for viewing forums, creating posts. Also, use memorization pattern for current forum/current post. Improve forum pagination efficiency.
Also fixed a bug with liking forum posts.
=> Forum optimizations

app/controllers/api/v2/forums_controller.rb, app/decorators/forum_decorator.rb, app/models/forum.rb, app/models/forum_post.rb, app/models/user.rb, app/models/user_forum_view.rb, db/migrate/20200304060935_update_user_forum_view.rb, db/structure.sql
Use an actual table for user forum views, instead of jsonb
Fix forum scoping
A bit more caching
=> More forum performance work

app/controllers/api/v2/seamail_controller.rb, app/decorators/seamail_decorator.rb, app/models/forum_post.rb, app/models/seamail.rb, db/migrate/20200304233439_forum_post_date_index.rb, db/migrate/20200304234553_photo_metadata_sequential_uuids.rb, db/structure.sql
Better index on forum posts
Sequential UUIDs for photos
Seamail optimizations
=> Performance tweaks

nginx.txt, twitarr.service
Add sample configs for systemd and nginx
=> systemd and nginx configs

app/models/post_reaction.rb
=> Remove redundant presence validator
